let audioCtx, masterGain, recorder, intervalId;
let isPlaying=false,currentStep=0,chunks=[],plugins=[],scaleLock=true,isPointerDown=false,pointerPaintValue=true;
const noteNames=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
const pianoNotes=["B5","A#5","A5","G#5","G5","F#5","F5","E5","D#5","D5","C#5","C5","B4","A#4","A4","G#4","G4","F#4","F4","E4","D#4","D4","C#4","C4"];
const scales={minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],harmonicMinor:[0,2,3,5,7,8,11],pentatonic:[0,3,5,7,10]};
const baseFreq={C:261.63,"C#":277.18,D:293.66,"D#":311.13,E:329.63,F:349.23,"F#":369.99,G:392,"G#":415.3,A:440,"A#":466.16,B:493.88};
let channels=[
 {name:"Kick",type:"drum",sound:"kick",pattern:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],notes:{}},
 {name:"Snare",type:"drum",sound:"snare",pattern:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],notes:{}},
 {name:"Hi-Hat",type:"drum",sound:"hat",pattern:[1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1],notes:{}},
 {name:"Clap/Perc",type:"drum",sound:"clap",pattern:[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],notes:{}},
 {name:"808",type:"bass",sound:"808",pattern:[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],notes:{}},
 {name:"Bass",type:"bass",sound:"bass",pattern:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],notes:{}},
 {name:"Melody",type:"synth",sound:"melody",pattern:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],notes:{}},
 {name:"Piano",type:"piano",sound:"piano",pattern:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],notes:{}},
 {name:"Synth",type:"synth",sound:"synth",pattern:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],notes:{}}
];
let selectedChannel=0;

function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=.82;masterGain.connect(audioCtx.destination)}
function route(src){let node=src;plugins.forEach(p=>{if(p.enabled&&p.input&&p.output){node.connect(p.input);node=p.output}});node.connect(masterGain)}
function freq(note){let n=note.slice(0,-1),oct=Number(note.slice(-1));return baseFreq[n]*Math.pow(2,oct-4)}
function drum(type,time){initAudio();if(type==="kick"||type==="808"||type==="bass"){const o=audioCtx.createOscillator(),g=audioCtx.createGain();let tune=type==="808"?Number(bassTune.value):type==="bass"?55:140;o.type=type==="kick"?"triangle":"sine";o.frequency.setValueAtTime(tune,time);o.frequency.exponentialRampToValueAtTime(type==="kick"?45:38,time+(type==="kick"?.18:.5));g.gain.setValueAtTime(type==="kick"?1:.85,time);g.gain.exponentialRampToValueAtTime(.001,time+(type==="kick"?.22:.65));o.connect(g);route(g);o.start(time);o.stop(time+(type==="kick"?.25:.7));return}const len=audioCtx.sampleRate*(type==="hat"?.055:.18),b=audioCtx.createBuffer(1,len,audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;const s=audioCtx.createBufferSource(),f=audioCtx.createBiquadFilter(),g=audioCtx.createGain();s.buffer=b;f.type="highpass";f.frequency.value=type==="hat"?6200:760;g.gain.value=type==="hat"?.32:.68;s.connect(f).connect(g);route(g);s.start(time)}
function synthNote(note,time,dur=.24,wave=None){initAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=wave||waveform.value;o.frequency.value=freq(note);g.gain.setValueAtTime(.001,time);g.gain.exponentialRampToValueAtTime(.42,time+.015);g.gain.exponentialRampToValueAtTime(.001,time+dur);o.connect(g);route(g);o.start(time);o.stop(time+dur+.05)}
function renderSequencer(){sequencer.innerHTML="";channels.forEach((c,ci)=>{const row=document.createElement("div");row.className="track";row.innerHTML=`<strong>${c.name}</strong>`;c.pattern.forEach((on,si)=>{const st=document.createElement("div");st.className="step"+(on?" on":"");st.dataset.step=si;st.addEventListener("pointerdown",()=>{c.pattern[si]=c.pattern[si]?0:1;renderSequencer()});row.appendChild(st)});const edit=document.createElement("button");edit.className="edit-channel";edit.textContent="Edit";edit.onclick=()=>{selectedChannel=ci;syncChannelSelect();showPage("piano")};row.appendChild(edit);sequencer.appendChild(row)});renderChannelSelect()}
function renderChannelSelect(){channelSelect.innerHTML="";channels.forEach((c,i)=>{const o=document.createElement("option");o.value=i;o.textContent=c.name;channelSelect.appendChild(o)});channelSelect.value=selectedChannel}
function syncChannelSelect(){renderChannelSelect();renderPianoRoll()}
function isAllowed(note){const root=noteNames.indexOf(rootSelect.value),n=note.slice(0,-1);return scales[scaleSelect.value].includes((noteNames.indexOf(n)-root+12)%12)}
function keyFor(note,step){return `${note}_${step}`}
function renderPianoRoll(){pianoRoll.innerHTML="";const ch=channels[selectedChannel];pianoNotes.forEach(note=>{const lab=document.createElement("div");lab.className="note-label";lab.textContent=note;pianoRoll.appendChild(lab);for(let i=0;i<32;i++){const cell=document.createElement("div");const allowed=isAllowed(note);cell.className="cell"+(allowed?" allowed":"")+(ch.notes[keyFor(note,i)]?" on":"");cell.dataset.note=note;cell.dataset.step=i;const paint=()=>{if(scaleLock&&!allowed)return;const k=keyFor(note,i);ch.notes[k]=pointerPaintValue;if(ch.notes[k])cell.classList.add("on");else cell.classList.remove("on")};cell.addEventListener("pointerdown",e=>{isPointerDown=true;pointerPaintValue=!cell.classList.contains("on");paint();cell.setPointerCapture?.(e.pointerId)});cell.addEventListener("pointerenter",()=>{if(isPointerDown)paint()});cell.addEventListener("pointerup",()=>isPointerDown=false);pianoRoll.appendChild(cell)}})}
window.addEventListener("pointerup",()=>isPointerDown=false);
function tick(){const bpm=Number(document.getElementById("bpm").value),stepMs=(60/bpm/4)*1000,time=audioCtx.currentTime;document.querySelectorAll(".step").forEach(s=>s.classList.remove("playing"));document.querySelectorAll(`[data-step="${currentStep%16}"]`).forEach(s=>s.classList.add("playing"));channels.forEach(c=>{if(c.pattern[currentStep%16])drum(c.sound,time);Object.keys(c.notes).forEach(k=>{const [note,st]=k.split("_");if(Number(st)===currentStep && c.notes[k]){if(c.sound==="808"||c.sound==="bass")drum(c.sound,time);else synthNote(note,time,.28,c.sound==="piano"?"triangle":waveform.value)}})});currentStep=(currentStep+1)%32;intervalId=setTimeout(tick,stepMs)}
function play(){initAudio();if(audioCtx.state==="suspended")audioCtx.resume();if(isPlaying)return;isPlaying=true;currentStep=0;tick()}
function stop(){isPlaying=false;clearTimeout(intervalId);document.querySelectorAll(".step").forEach(s=>s.classList.remove("playing"))}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".side").forEach(s=>s.classList.remove("active"));document.querySelectorAll(`.side[data-page="${id}"]`).forEach(s=>s.classList.add("active"))}
function renderKeyboard(){noteNames.forEach(n=>{const k=document.createElement("button");k.className="key"+(n.includes("#")?" black":"");k.textContent=n;k.onclick=()=>synthNote(n+"4",audioCtx?audioCtx.currentTime:(initAudio(),audioCtx.currentTime),.45);keyboard.appendChild(k)})}
function generateChords(){const ch=channels[selectedChannel];ch.notes={};const root=rootSelect.value;const rootIdx=noteNames.indexOf(root);const chordSteps=scaleSelect.value==="major"?[0,4,7]:[0,3,7];[0,8,16,24].forEach(step=>{chordSteps.forEach(int=>{const n=noteNames[(rootIdx+int)%12]+"4";ch.notes[keyFor(n,step)]=true;ch.notes[keyFor(n,step+1)]=true;ch.notes[keyFor(n,step+2)]=true})});renderPianoRoll()}
function renderPlaylist(){playlistGrid.innerHTML="";["Drums","808","Bass","Melody","Piano","Synth","Vocal","FX"].forEach((row,r)=>{const lab=document.createElement("div");lab.className="bar-label";lab.textContent=row;playlistGrid.appendChild(lab);for(let i=0;i<16;i++){const c=document.createElement("div");c.className=(i%4===0||r<2)?"clip":"cell";c.onclick=()=>c.classList.toggle("on");playlistGrid.appendChild(c)}})}
function renderMixer(){mixerBoard.innerHTML="";["Master","Kick","Snare","Hats","808","Bass","Melody","Piano","Synth","Vocal","FX"].forEach(n=>{const ch=document.createElement("div");ch.className="channel";ch.innerHTML=`<strong>${n}</strong><br><input class="fader" type="range" min="0" max="1" step=".01" value=".8"><div class="fxslot">EQ</div><div class="fxslot">Compressor</div><div class="fxslot">Reverb</div><div class="fxslot">Delay</div>`;mixerBoard.appendChild(ch)})}
function renderSamples(){const data={kicks:["Hard Kick 01","Soft Kick 02","Boom Kick"],eight:["Sub 808","Glide 808","Distorted 808"],snare:["Trap Snare","R&B Clap","Rim Shot"],hat:["Closed Hat","Open Hat","Afro Shaker","Perc Wood"],fx:["Riser","Impact","Vocal Chop","Reverse FX"]};[["kicksList",data.kicks],["eightList",data.eight],["snareList",data.snare],["hatList",data.hat],["fxList",data.fx]].forEach(([id,arr])=>{document.getElementById(id).innerHTML="";arr.forEach(x=>{const b=document.createElement("button");b.className="sample";b.textContent=x;b.onclick=()=>drum(x.includes("808")?"808":x.includes("Kick")?"kick":x.includes("Hat")||x.includes("Shaker")?"hat":"snare",audioCtx?audioCtx.currentTime:(initAudio(),audioCtx.currentTime));document.getElementById(id).appendChild(b)})})}
function renderPresets(){["Serum Style Lead","Nexus Style Bell","Omnisphere Style Pad","Analog Bass","Warm Piano","808s Robotic Synth","Afro Pluck","R&B Keys"].forEach((p,i)=>{const d=document.createElement("div");d.className="preset";d.textContent=p;d.onclick=()=>{document.querySelectorAll(".preset").forEach(x=>x.classList.remove("active"));d.classList.add("active");waveform.value=i%3===0?"sawtooth":i%3===1?"sine":"triangle"};presetGrid.appendChild(d)})}
async function toggleRecord(){initAudio();if(recorder&&recorder.state==="recording"){recorder.stop();recBtn.textContent="●";startRec2.textContent="Record Vocal";return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{recording.src=URL.createObjectURL(new Blob(chunks,{type:"audio/webm"}))};recorder.start();recBtn.textContent="■";startRec2.textContent="Stop Recording"}
function renderVocalChain(){const preset=vocalPreset.value;const chain=preset.includes("Robotic")?["AutoTune Fast","EQ Telephone","Compressor","Chorus","Reverb"]:preset.includes("Trap")?["AutoTune Medium","EQ Bright","Compressor","De-Esser","Delay"]:preset.includes("R&B")?["AutoTune Soft","EQ Warm","Compressor","Plate Reverb","Stereo Widener"]:preset.includes("Adlib")?["AutoTune Fast","Highpass","Ping Pong Delay","Wide Chorus","Reverb"]:["EQ Clean","Compressor","Light Reverb"];vocalChain.innerHTML="";chain.forEach(x=>{const d=document.createElement("div");d.className="chain-item";d.textContent=x;vocalChain.appendChild(d)})}
function addPlugin(p){plugins.push(p)}
function exportJson(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:"application/json"});downloadLink.href=URL.createObjectURL(blob);downloadLink.download=name;downloadLink.textContent=`Download ${name}`}
function exportWavDemo(){initAudio();const sr=44100,dur=2,buf=new ArrayBuffer(44+sr*dur*2),view=new DataView(buf);function w(o,s){for(let i=0;i<s.length;i++)view.setUint8(o+i,s.charCodeAt(i))}w(0,"RIFF");view.setUint32(4,36+sr*dur*2,true);w(8,"WAVEfmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sr,true);view.setUint32(28,sr*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);w(36,"data");view.setUint32(40,sr*dur*2,true);let off=44;for(let i=0;i<sr*dur;i++){let sample=Math.sin(2*Math.PI*220*i/sr)*0.25;view.setInt16(off,sample*32767,true);off+=2}const blob=new Blob([view],{type:"audio/wav"});downloadLink.href=URL.createObjectURL(blob);downloadLink.download="ks-studio-demo.wav";downloadLink.textContent="Download ks-studio-demo.wav"}
function projectData(){return {name:"K’s Studio Project",bpm:bpm.value,scale:scaleSelect.value,root:rootSelect.value,channels,theme:document.documentElement.dataset.theme}}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>{document.documentElement.dataset.theme=b.dataset.theme;localStorage.setItem("ks-theme",b.dataset.theme)});
document.documentElement.dataset.theme=localStorage.getItem("ks-theme")||"orange-dark";
playBtn.onclick=()=>isPlaying?stop():play();stopBtn.onclick=stop;recBtn.onclick=toggleRecord;startRec2.onclick=toggleRecord;channelSelect.onchange=e=>{selectedChannel=Number(e.target.value);renderPianoRoll()};scaleSelect.onchange=renderPianoRoll;rootSelect.onchange=renderPianoRoll;scaleLockBtn.onclick=()=>{scaleLock=!scaleLock;scaleLockBtn.textContent=`Scale Lock: ${scaleLock?"ON":"OFF"}`};chordBtn.onclick=generateChords;clearRollBtn.onclick=()=>{channels[selectedChannel].notes={};renderPianoRoll()};duplicatePattern.onclick=()=>channels.forEach(c=>c.pattern=[...c.pattern]);addSynth.onclick=()=>{channels.push({name:"Synth "+(channels.length+1),type:"synth",sound:"synth",pattern:Array(16).fill(0),notes:{}});renderSequencer()};addMelody.onclick=()=>{channels.push({name:"Melody "+(channels.length+1),type:"synth",sound:"melody",pattern:Array(16).fill(0),notes:{}});renderSequencer()};addClipBtn.onclick=renderPlaylist;clearPlaylistBtn.onclick=()=>{document.querySelectorAll(".clip,.playlist-grid .cell").forEach(c=>c.classList.remove("on"))};test808.onclick=()=>drum("808",audioCtx?audioCtx.currentTime:(initAudio(),audioCtx.currentTime));vocalPreset.onchange=renderVocalChain;saveProjectBtn.onclick=()=>{localStorage.setItem("ksProject",JSON.stringify(projectData()));alert("Project saved on this device")};loadProjectBtn.onclick=()=>{const p=JSON.parse(localStorage.getItem("ksProject")||"null");if(!p)return alert("No saved project");channels=p.channels;bpm.value=p.bpm;scaleSelect.value=p.scale;rootSelect.value=p.root;renderSequencer();renderPianoRoll();alert("Project loaded")};exportMidiBtn.onclick=()=>exportJson("ks-midi-like.json",projectData());exportStemsBtn.onclick=()=>exportJson("ks-stems.json",{channels:channels.map(c=>({name:c.name,pattern:c.pattern,notes:c.notes}))});exportWavBtn.onclick=exportWavDemo;
sampleUpload.onchange=e=>{[...e.target.files].forEach(f=>{const b=document.createElement("button");b.className="sample";b.textContent=f.name;const url=URL.createObjectURL(f);b.onclick=()=>{initAudio();fetch(url).then(r=>r.arrayBuffer()).then(ab=>audioCtx.decodeAudioData(ab)).then(buffer=>{const src=audioCtx.createBufferSource();src.buffer=buffer;route(src);src.start()})};fxList.appendChild(b)})};
document.addEventListener("keydown",e=>{if(["INPUT","SELECT","TEXTAREA"].includes(document.activeElement.tagName))return;if(e.code==="Space"){e.preventDefault();isPlaying?stop():play()}if(e.key==="Escape")stop();if(e.key.toLowerCase()==="r")toggleRecord();const map={a:"C",w:"C#",s:"D",e:"D#",d:"E",f:"F",t:"F#",g:"G",y:"G#",h:"A",u:"A#",j:"B"};if(map[e.key.toLowerCase()])synthNote(map[e.key.toLowerCase()]+"4",audioCtx?audioCtx.currentTime:(initAudio(),audioCtx.currentTime),.35);if(/[1-9]/.test(e.key)){selectedChannel=Math.min(Number(e.key)-1,channels.length-1);syncChannelSelect()}});
renderSequencer();renderKeyboard();renderPianoRoll();renderPlaylist();renderMixer();renderSamples();renderPresets();renderVocalChain();
